server:
    port: 8000
spring:
    profiles:
        active: dev

    jpa:
        open-in-view: false


---

spring:
    datasource:
        password: ${MYSQL_ROOT_PASSWORD}
        url: jdbc:mysql://${MYSQL_HOST}/dcbapp-qa
        username: ${MYSQL_ROOT_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: dev
welcome:
    message: '"API"'

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
    datasource:
        password: ${MYSQL_ROOT_PASSWORD}
        url: jdbc:mysql://${MYSQL_HOST}/dcbapp-qa
        username: ${MYSQL_ROOT_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: qa
welcome:
    message: '"Hello and Welcome to my API"'

---

spring:
    datasource:
        password: ${MYSQL_ROOT_PASSWORD}
        url: jdbc:mysql://${MYSQL_HOST}/dcbapp-qa
        username: ${MYSQL_ROOT_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: prod
welcome:
    message: '"Hello and Welcome to my API"'
